[package]
name = "farkle"
version = "0.2.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
colored = "2"
crossterm = "0.23.2"
rand = "0.7.3"
getch = "0.3.1"
